CREATE TABLE [dbo].[CardType]
(
	[Id] INT NOT NULL, 
    [Name] NVARCHAR(10) NOT NULL, 
    [CreatedDate] DATETIME2 NOT NULL CONSTRAINT [DC_CardType_CreatedDate] DEFAULT GETUTCDATE(), 
    [ModifiedDate] DATETIME2 NOT NULL CONSTRAINT [DC_CardType_ModifiedDate] DEFAULT GETUTCDATE(),
	CONSTRAINT [PK_CardType] PRIMARY KEY CLUSTERED ([Id] ASC)
);